/**
 * Hook server — Gemini & Codex CLI hook injection adapters.
 *
 * Generates shell stub scripts and injects command-type hooks into
 * Gemini (~/.gemini/settings.json) and Codex (~/.codex/hooks.json)
 * CLI config files.
 *
 * Extracted from hookServer-inject.ts (T1902) to keep file size under 400 lines.
 *
 * @module hookServer-inject-adapters
 */
import { join, dirname } from 'path'
import { readFile, writeFile, mkdir } from 'fs/promises'
import { HOOK_PORT } from './hookServer-inject'
// Re-export so tests/consumers can import alongside adapter functions
export { HOOK_PORT } from './hookServer-inject'

// ── Types (shared with hookServer-inject) ────────────────────────────────────

interface HookEntry {
  type: string
  url?: string
  headers?: Record<string, string>
  command?: string
  timeout?: number
}

interface HookGroup {
  hooks?: HookEntry[]
}

interface ClaudeSettings {
  hooks?: Record<string, HookGroup[]>
}

// ── Gemini / Codex hook injection ────────────────────────────────────────────

/**
 * Gemini CLI hook events → KanbAgent hook route mapping.
 * Gemini uses these event names in ~/.gemini/settings.json.
 */
const GEMINI_HOOK_EVENTS: Array<{ event: string; route: string }> = [
  { event: 'SessionStart', route: '/hooks/session-start' },
  { event: 'SessionEnd',   route: '/hooks/stop' },
  { event: 'BeforeTool',   route: '/hooks/pre-tool-use' },
  { event: 'AfterTool',    route: '/hooks/post-tool-use' },
]

/**
 * Codex CLI hook events → KanbAgent hook route mapping.
 * Codex uses these event names in ~/.codex/hooks.json.
 * NOTE: hooks.json format is based on available doc hints — verify against
 * https://developers.openai.com/codex/hooks if it changes between CLI versions.
 */
const CODEX_HOOK_EVENTS: Array<{ event: string; route: string }> = [
  { event: 'SessionStart', route: '/hooks/session-start' },
  { event: 'Stop',         route: '/hooks/stop' },
  { event: 'PreToolUse',   route: '/hooks/pre-tool-use' },
  { event: 'PostToolUse',  route: '/hooks/post-tool-use' },
]

/**
 * Generate a platform-appropriate shell stub script that reads JSON from
 * stdin and POSTs it to the KanbAgent hookServer.
 *
 * On Windows: generates a .cmd file using curl (built-in since Windows 10 1803).
 * On Unix/WSL: generates a .sh file using curl.
 *
 * Always regenerated on startup so the embedded IP/secret stays current.
 * The output directory is created if missing.
 */
export async function generateHookStub(
  outputPath: string,
  ip: string,
  port: number,
  route: string,
  secret: string
): Promise<void> {
  await mkdir(dirname(outputPath), { recursive: true })
  let script: string
  if (process.platform === 'win32') {
    // Windows-native: curl is available since Windows 10 build 1803.
    script = [
      '@echo off',
      `curl -s -X POST "http://${ip}:${port}${route}" ^`,
      `  -H "Authorization: Bearer ${secret}" ^`,
      '  -H "Content-Type: application/json" ^',
      '  --data-binary @-',
      ''
    ].join('\r\n')
  } else {
    script = [
      '#!/bin/sh',
      '# Generated by KanbAgent — do not edit',
      `curl -s -X POST "http://${ip}:${port}${route}" \\`,
      `  -H "Authorization: Bearer ${secret}" \\`,
      '  -H "Content-Type: application/json" \\',
      '  -d @-',
      ''
    ].join('\n')
  }
  await writeFile(outputPath, script, { mode: 0o755 })
}

/**
 * Inject Gemini CLI lifecycle hooks into the given settings.json path
 * (typically ~/.gemini/settings.json).
 *
 * Uses command-type hooks with shell stubs stored in `stubsDir`.
 * The JSON structure is identical to Claude Code settings.json (hook groups).
 * Idempotent: does not add duplicate command entries for the same stub path.
 * Always regenerates stub scripts to embed the current IP/secret.
 *
 * Best-effort: silently skips on unrecoverable read errors.
 */
export async function injectGeminiHooks(
  settingsPath: string,
  ip: string,
  secret: string,
  stubsDir: string,
  port: number = HOOK_PORT
): Promise<void> {
  let settings: ClaudeSettings = {}
  let fileExists = true

  try {
    const raw = await readFile(settingsPath, 'utf-8')
    settings = JSON.parse(raw)
  } catch (err: unknown) {
    const code = (err as NodeJS.ErrnoException)?.code
    if (code === 'ENOENT') {
      fileExists = false
    } else {
      console.warn('[hookServer] Could not read Gemini settings:', err)
      return
    }
  }

  let changed = false
  if (!settings.hooks) {
    settings.hooks = {}
  }

  const ext = process.platform === 'win32' ? '.cmd' : '.sh'

  for (const { event, route } of GEMINI_HOOK_EVENTS) {
    const stubPath = join(stubsDir, `gemini-${event.toLowerCase()}${ext}`)
    // Always regenerate stub so IP/secret/port stay current
    await generateHookStub(stubPath, ip, port, route, secret).catch(
      (err) => console.warn(`[hookServer] Could not generate Gemini stub for ${event}:`, err)
    )

    if (!settings.hooks![event]) {
      settings.hooks![event] = [{ hooks: [{ type: 'command', command: stubPath, timeout: 5000 }] }]
      changed = true
    } else {
      const groups = settings.hooks![event]
      const hasOurCommand = groups.some(
        (g) => Array.isArray(g.hooks) && g.hooks.some((h) => h.type === 'command' && h.command === stubPath)
      )
      if (!hasOurCommand) {
        groups.push({ hooks: [{ type: 'command', command: stubPath, timeout: 5000 }] })
        changed = true
      }
    }
  }

  if (changed || !fileExists) {
    if (!fileExists) {
      await mkdir(dirname(settingsPath), { recursive: true })
    }
    await writeFile(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8')
    console.log('[hookServer] Updated Gemini hooks:', settingsPath, '| created:', !fileExists)
  }
}

/**
 * Inject Codex CLI lifecycle hooks into the given hooks.json path
 * (typically ~/.codex/hooks.json).
 *
 * No-op on Windows native: Codex hooks are disabled on Windows (WSL only).
 * Idempotent: does not overwrite existing entries pointing to the same stub.
 * Always regenerates stub scripts to embed the current IP/secret.
 *
 * hooks.json format: flat JSON object mapping event names to command paths.
 * Verify format against https://developers.openai.com/codex/hooks if needed.
 *
 * Best-effort: silently skips on unrecoverable read errors.
 */
export async function injectCodexHooks(
  hooksPath: string,
  ip: string,
  secret: string,
  stubsDir: string,
  port: number = HOOK_PORT
): Promise<void> {
  // Codex hooks are WSL/Linux only — skip on Windows native
  if (process.platform === 'win32') return

  let hooks: Record<string, string> = {}
  let fileExists = true

  try {
    const raw = await readFile(hooksPath, 'utf-8')
    hooks = JSON.parse(raw)
  } catch (err: unknown) {
    const code = (err as NodeJS.ErrnoException)?.code
    if (code === 'ENOENT') {
      fileExists = false
    } else {
      console.warn('[hookServer] Could not read Codex hooks:', err)
      return
    }
  }

  let changed = false

  for (const { event, route } of CODEX_HOOK_EVENTS) {
    const stubPath = join(stubsDir, `codex-${event.toLowerCase()}.sh`)
    // Always regenerate stub so IP/secret/port stay current
    await generateHookStub(stubPath, ip, port, route, secret).catch(
      (err) => console.warn(`[hookServer] Could not generate Codex stub for ${event}:`, err)
    )

    if (hooks[event] !== stubPath) {
      hooks[event] = stubPath
      changed = true
    }
  }

  if (changed || !fileExists) {
    if (!fileExists) {
      await mkdir(dirname(hooksPath), { recursive: true })
    }
    await writeFile(hooksPath, JSON.stringify(hooks, null, 2) + '\n', 'utf-8')
    console.log('[hookServer] Updated Codex hooks:', hooksPath, '| created:', !fileExists)
  }
}
